name: CI

on:
  push:
    branches-ignore:
      - master

env:
  node-version: '20.x'

jobs:
  precheck:
    name: Check jobs to run
    runs-on: ubuntu-22.04
    outputs:
      affected-nx-graphql-code-generator: ${{ steps.affected.outputs.nx-graphql-code-generator }}
      affected-nx-graphql-code-generator-e2e: ${{ steps.affected.outputs.nx-graphql-code-generator-e2e }}
      affected-nx-dev-tools: ${{ steps.affected.outputs.nx-dev-tools }}
      affected-nx-dev-tools-e2e: ${{ steps.affected.outputs.nx-dev-tools-e2e }}
      affected-eslint-config: ${{ steps.affected.outputs.eslint-config }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Check affected projects
        id: affected
        run: |
          yarn --silent nx show projects --affected --type=lib --base=origin/master --select=projects
          echo "END"
          echo "nx-graphql-code-generator=$(./tools/bin/check-affected.sh lib nx-graphql-code-generator origin/master)" >> $GITHUB_OUTPUT
          echo "nx-graphql-code-generator-e2e=$(./tools/bin/check-affected.sh lib nx-graphql-code-generator-e2e origin/master)" >> $GITHUB_OUTPUT
          echo "nx-dev-tools=$(./tools/bin/check-affected.sh lib nx-dev-tools origin/master)" >> $GITHUB_OUTPUT
          echo "nx-dev-tools-e2e=$(./tools/bin/check-affected.sh lib nx-dev-tools-e2e origin/master)" >> $GITHUB_OUTPUT
          echo "eslint-config=$(./tools/bin/check-affected.sh lib eslint-config origin/master)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  nx-graphql-code-generator:
    name:
    runs-on: ubuntu-22.04
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-nx-graphql-code-generator == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn nx lint nx-graphql-code-generator

      - name: Test
        run: yarn nx test nx-graphql-code-generator

      - name: Build
        run: yarn nx build nx-graphql-code-generator

  nx-graphql-code-generator-e2e:
    name:
    runs-on: ubuntu-22.04
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-nx-graphql-code-generator == 'true' || needs.precheck.outputs.affected-nx-graphql-code-generator-e2e == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: e2e
        run: yarn nx e2e nx-graphql-code-generator-e2e

  nx-dev-tools:
    name:
    runs-on: ubuntu-22.04
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-nx-dev-tools == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn nx lint nx-dev-tools

      - name: Test
        run: yarn nx test nx-dev-tools

      - name: Build
        run: yarn nx build nx-dev-tools

  nx-dev-tools-e2e:
    name:
    runs-on: ubuntu-22.04
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-nx-dev-tools == 'true' || needs.precheck.outputs.affected-nx-dev-tools-e2e == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: e2e
        run: yarn nx e2e nx-dev-tools-e2e

  eslint-config:
    runs-on: ubuntu-22.04
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-eslint-config == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn nx lint eslint-config

      - name: Build
        run: yarn nx build eslint-config
