name: 'Release'

on:
  push:
    branches:
      - master

env:
  npm-token: ${{ secrets.NPM_TOKEN }}
  github-token: ${{ secrets.GITHUB_TOKEN }}
  node-version: '14.x'

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install packages
        run: yarn install --prefer-offline

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: 'chore(release): update packages versions'
          title: 'Upcoming Release Changes'
        env:
          GITHUB_TOKEN: ${{ env.github-token }}
          NPM_TOKEN: ${{ env.npm-token }}
